=== dhananjay4985/wsclient/WSClientExample/src/main/resources/wsdl/GetInstalledBaseResponse-v1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             Get Installed Base Response v1.1                            -->
<!-- Transaction:         IB - Installed Base                                         -->
<!-- Datamodel:           ZSmart Communication Datamodel, version 1.0                 -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     KpnML                                                       -->
<!-- Generated at:        08-12-2016 17:32:05                                         -->
<!-- Generated using:     EC-Design 1.6.1* (http://www.ec-design.nl)                  -->
<!-- Generated by:        Frans van Basten                                            -->
<!-- Organisation:        KPN (KPN)                                                   -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://services.kpn.com/Messages/GetInstalledBaseResponse-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1"
		xmlns:str="http://services.kpn.com/Messages/GetInstalledBaseResponse-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="GetInstalledBaseResponse-v1">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="OrigReqerId" type="str:TypeWsoId">
					<xsd:annotation>
						<xsd:documentation>Original Requester ID</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:choice>
					<xsd:element name="Cust">
						<xsd:annotation>
							<xsd:documentation>CUSTOMER</xsd:documentation>
						</xsd:annotation>
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="CustId" type="str:TypeCustId">
									<xsd:annotation>
										<xsd:documentation>Customer ID</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="Prod" minOccurs="0" maxOccurs="unbounded">
									<xsd:annotation>
										<xsd:documentation>customer - PRODUCT</xsd:documentation>
									</xsd:annotation>
									<xsd:complexType>
										<xsd:sequence>
											<xsd:element name="ProdType" minOccurs="0" type="str:TypeProdType">
												<xsd:annotation>
													<xsd:documentation>Product type</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="ProdCd" minOccurs="0" type="str:TypeProdCd">
												<xsd:annotation>
													<xsd:documentation>Product Code</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="ComName" type="str:TypeText100">
												<xsd:annotation>
													<xsd:documentation>Commercial name</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="InstId" type="str:TypeProdInstId">
												<xsd:annotation>
													<xsd:documentation>Instance ID</xsd:documentation>
												</xsd:annotation>
											</xsd:element>
											<xsd:element name="ProdRelParent" minOccurs="0">
												<xsd:annotation>
													<xsd:documentation>customer - product - PRODUCT RELATION (PARENT)</xsd:documentation>
												</xsd:annotation>
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="ProdCd" minOccurs="0" type="str:TypeProdCd">
															<xsd:annotation>
																<xsd:documentation>Product Code</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
														<xsd:element name="InstId" type="str:TypeProdInstId">
															<xsd:annotation>
																<xsd:documentation>Instance ID</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Attr" minOccurs="0" maxOccurs="unbounded">
												<xsd:annotation>
													<xsd:documentation>customer - product - ATTRIBUTE</xsd:documentation>
												</xsd:annotation>
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="AttrCd" type="str:TypeProdAttrCd">
															<xsd:annotation>
																<xsd:documentation>Attribute Code</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
														<xsd:element name="AttrVal" type="str:TypeProdAttrVal">
															<xsd:annotation>
																<xsd:documentation>Attribute Value</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
											<xsd:element name="Cfs" minOccurs="0" maxOccurs="unbounded">
												<xsd:annotation>
													<xsd:documentation>customer - product - CUSTOMER FACING SERVICE</xsd:documentation>
												</xsd:annotation>
												<xsd:complexType>
													<xsd:sequence>
														<xsd:element name="CfsType" minOccurs="0" type="str:TypeCfsType">
															<xsd:annotation>
																<xsd:documentation>Customer Facing Service Type</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
														<xsd:element name="CfsCd" minOccurs="0" type="str:TypeProdCd">
															<xsd:annotation>
																<xsd:documentation>Customer Facing Service Code</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
														<xsd:element name="ComName" type="str:TypeText100">
															<xsd:annotation>
																<xsd:documentation>Commercial name</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
														<xsd:element name="InstId" type="str:TypeProdInstId">
															<xsd:annotation>
																<xsd:documentation>Instance ID</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
														<xsd:element name="CfsInstStat" type="str:TypeCfsInstStat">
															<xsd:annotation>
																<xsd:documentation>Customer facing service instance status</xsd:documentation>
															</xsd:annotation>
														</xsd:element>
														<xsd:element name="CfsRelParent" minOccurs="0">
															<xsd:annotation>
																<xsd:documentation>customer - product - customer facing service - CUSTOMER FACING SERVICE RELATION (PARENT)</xsd:documentation>
															</xsd:annotation>
															<xsd:complexType>
																<xsd:sequence>
																	<xsd:element name="CfsCd" minOccurs="0" type="str:TypeProdCd">
																		<xsd:annotation>
																			<xsd:documentation>Customer Facing Service Code</xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																	<xsd:element name="InstId" type="str:TypeProdInstId">
																		<xsd:annotation>
																			<xsd:documentation>Instance ID</xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																</xsd:sequence>
															</xsd:complexType>
														</xsd:element>
														<xsd:element name="Attr" minOccurs="0" maxOccurs="unbounded">
															<xsd:annotation>
																<xsd:documentation>customer - product - customer facing service - ATTRIBUTE</xsd:documentation>
															</xsd:annotation>
															<xsd:complexType>
																<xsd:sequence>
																	<xsd:element name="AttrCd" type="str:TypeProdAttrCd">
																		<xsd:annotation>
																			<xsd:documentation>Attribute Code</xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																	<xsd:element name="AttrVal" type="str:TypeProdAttrVal">
																		<xsd:annotation>
																			<xsd:documentation>Attribute Value</xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																</xsd:sequence>
															</xsd:complexType>
														</xsd:element>
														<xsd:element name="Rfs" minOccurs="0" maxOccurs="unbounded">
															<xsd:annotation>
																<xsd:documentation>customer - product - customer facing service - RESOURCE FACING SERVICE</xsd:documentation>
															</xsd:annotation>
															<xsd:complexType>
																<xsd:sequence>
																	<xsd:element name="RfsCd" minOccurs="0" type="str:TypeProdCd">
																		<xsd:annotation>
																			<xsd:documentation>Resource Facing Service Code</xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																	<xsd:element name="ComName" type="str:TypeText100">
																		<xsd:annotation>
																			<xsd:documentation>Commercial name</xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																	<xsd:element name="InstId" type="str:TypeProdInstId">
																		<xsd:annotation>
																			<xsd:documentation>Instance ID</xsd:documentation>
																		</xsd:annotation>
																	</xsd:element>
																	<xsd:element name="Attr" minOccurs="0" maxOccurs="unbounded">
																		<xsd:annotation>
																			<xsd:documentation>customer - product - customer facing service - resource facing service - ATTRIBUTE</xsd:documentation>
																		</xsd:annotation>
																		<xsd:complexType>
																			<xsd:sequence>
																				<xsd:element name="AttrCd" type="str:TypeProdAttrCd">
																					<xsd:annotation>
																						<xsd:documentation>Attribute Code</xsd:documentation>
																					</xsd:annotation>
																				</xsd:element>
																				<xsd:element name="AttrVal" type="str:TypeProdAttrVal">
																					<xsd:annotation>
																						<xsd:documentation>Attribute Value</xsd:documentation>
																					</xsd:annotation>
																				</xsd:element>
																			</xsd:sequence>
																		</xsd:complexType>
																	</xsd:element>
																</xsd:sequence>
															</xsd:complexType>
														</xsd:element>
													</xsd:sequence>
												</xsd:complexType>
											</xsd:element>
										</xsd:sequence>
									</xsd:complexType>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="Err" maxOccurs="unbounded">
						<xsd:annotation>
							<xsd:documentation>ERROR</xsd:documentation>
						</xsd:annotation>
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="ErrCd" type="str:TypeErrCd">
									<xsd:annotation>
										<xsd:documentation>Error Code</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="ErrMsg" type="str:TypeErrMsg">
									<xsd:annotation>
										<xsd:documentation>Error Message</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- CUSTOMER FACING SERVICE INSTANCE STATUS: FORMAT: AN..10 -->
	<xsd:simpleType name="TypeCfsInstStat">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
			<xsd:enumeration value="ACTIVE">
				<xsd:annotation>
					<xsd:documentation>Product or service is active</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="INACTIVE">
				<xsd:annotation>
					<xsd:documentation>Porduct or service is inactive</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PEND_INACT">
				<xsd:annotation>
					<xsd:documentation>Pending inactive</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PEND_RESUM">
				<xsd:annotation>
					<xsd:documentation>Product or service is pending for resume</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="PEND_SUSP">
				<xsd:annotation>
					<xsd:documentation>Product or service is pending for suspend</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SUSPEND">
				<xsd:annotation>
					<xsd:documentation>Product or service has been suspended</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- CUSTOMER FACING SERVICE TYPE: FORMAT: AN..10 -->
	<xsd:simpleType name="TypeCfsType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
			<xsd:enumeration value="MAIN">
				<xsd:annotation>
					<xsd:documentation>Main Customer Facing Service</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="RELATED">
				<xsd:annotation>
					<xsd:documentation>Related Customer Facing Service</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- CUSTOMER ID: FORMAT: AN..100 -->
	<xsd:simpleType name="TypeCustId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- ERROR CODE: FORMAT: AN..10 -->
	<xsd:simpleType name="TypeErrCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- ERROR MESSAGE: FORMAT: AN..255 -->
	<xsd:simpleType name="TypeErrMsg">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="255"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PRODUCT ATTRIBUTE CODE: FORMAT: AN..50 -->
	<xsd:simpleType name="TypeProdAttrCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="50"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PRODUCT ATTRIBUTE VALUE: FORMAT: AN..100 -->
	<xsd:simpleType name="TypeProdAttrVal">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PRODUCT CODE: FORMAT: AN..50 -->
	<xsd:simpleType name="TypeProdCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="50"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PRODUCT INSTANCE ID: FORMAT: AN..100 -->
	<xsd:simpleType name="TypeProdInstId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PRODUCT TYPE: FORMAT: AN..10 -->
	<xsd:simpleType name="TypeProdType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
			<xsd:enumeration value="BUNDLE">
				<xsd:annotation>
					<xsd:documentation>Bundle</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="RELA_PROD">
				<xsd:annotation>
					<xsd:documentation>Related product</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SUBS_PLAN">
				<xsd:annotation>
					<xsd:documentation>Subscription plan</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypeText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- WSO IDENTIFIER: FORMAT: AN..100 -->
	<xsd:simpleType name="TypeWsoId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== dhananjay4985/wsclient/WSClientExample/src/main/resources/wsdl/GetInstalledBaseResponse-v1.1-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             Get Installed Base Response v1.1                            -->
<!-- Transaction:         IB - Installed Base                                         -->
<!-- Datamodel:           ZSmart Communication Datamodel, version 1.0                 -->
<!-- XML tagset used:     KpnML                                                       -->
<!-- Generated at:        08-12-2016 17:32:05                                         -->
<!-- Generated using:     EC-Design 1.6.1* (http://www.ec-design.nl)                  -->
<!-- Generated by:        Frans van Basten                                            -->
<!-- Organisation:        KPN (KPN)                                                   -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<GetInstalledBaseResponse-v1 xsi:schemaLocation="http://services.kpn.com/Messages/GetInstalledBaseResponse-v1 GetInstalledBaseResponse-v1.1.xsd"
		xmlns="http://services.kpn.com/Messages/GetInstalledBaseResponse-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<OrigReqerId>ORIGREQID0H7G6F7B234C8A</OrigReqerId>
	<Cust>
		<CustId>CustomerID123456</CustId>
		<Prod>
			<ProdCd>PROD007</ProdCd>
			<ComName>Instant telephony</ComName>
			<InstId>PRODUCTINST123321</InstId>
			<ProdRelParent>
				<ProdCd>PROD007</ProdCd>
				<InstId>PRODUCTINST123321</InstId>
			</ProdRelParent>
			<Attr>
				<AttrCd>E001</AttrCd>
				<AttrVal>elated</AttrVal>
			</Attr>
			<Cfs>
				<CfsCd>SRV4005</CfsCd>
				<ComName>Instant telephony</ComName>
				<InstId>PRODUCTINST123321</InstId>
				<CfsInstStat>ACTIVE</CfsInstStat>
				<CfsRelParent>
					<CfsCd>SRV4005</CfsCd>
					<InstId>PRODUCTINST123321</InstId>
				</CfsRelParent>
				<Attr>
					<AttrCd>E002</AttrCd>
					<AttrVal>eloquent</AttrVal>
				</Attr>
				<Rfs>
					<RfsCd>RFSCODE001</RfsCd>
					<ComName>Instant telephony</ComName>
					<InstId>PRODUCTINST123321</InstId>
					<Attr>
						<AttrCd>E003</AttrCd>
						<AttrVal>embezzle</AttrVal>
					</Attr>
				</Rfs>
			</Cfs>
		</Prod>
	</Cust>
</GetInstalledBaseResponse-v1>
