=== dhananjay4985/wsclient/WSClientExample/src/main/resources/wsdl/GetInstalledBaseRequest-v1.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             Get Installed Base Request v1.1                             -->
<!-- Transaction:         IB - Installed Base                                         -->
<!-- Datamodel:           ZSmart Communication Datamodel, version 1.0                 -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     KpnML                                                       -->
<!-- Generated at:        08-12-2016 17:14:15                                         -->
<!-- Generated using:     EC-Design 1.6.1* (http://www.ec-design.nl)                  -->
<!-- Generated by:        Frans van Basten                                            -->
<!-- Organisation:        KPN (KPN)                                                   -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema targetNamespace="http://services.kpn.com/Messages/GetInstalledBaseRequest-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1"
		xmlns:str="http://services.kpn.com/Messages/GetInstalledBaseRequest-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="GetInstalledBaseRequest-v1">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="OrigReqerId" type="str:TypeWsoId">
					<xsd:annotation>
						<xsd:documentation>Original Requester ID</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="ReqParams">
					<xsd:annotation>
						<xsd:documentation>REQUEST PARAMETERS</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="ReqProdInstStat" type="str:ReqCfsInstStat">
								<xsd:annotation>
									<xsd:documentation>Requested product instance status</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="DateFrom" minOccurs="0" type="str:TypeDate10">
								<xsd:annotation>
									<xsd:documentation>Date from</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="DateTo" minOccurs="0" type="str:TypeDate10">
								<xsd:annotation>
									<xsd:documentation>Date to</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:choice>
					<xsd:element name="Prod">
						<xsd:annotation>
							<xsd:documentation>PRODUCT</xsd:documentation>
						</xsd:annotation>
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="ProdType">
									<xsd:annotation>
										<xsd:documentation>Product type</xsd:documentation>
									</xsd:annotation>
									<!-- PRODUCT TYPE: FORMAT: AN..10 (codelist subset) -->
									<xsd:simpleType>
										<xsd:restriction base="xsd:string">
											<xsd:maxLength value="10"/>
											<xsd:enumeration value="BUNDLE">
												<xsd:annotation>
													<xsd:documentation>Bundle</xsd:documentation>
												</xsd:annotation>
											</xsd:enumeration>
										</xsd:restriction>
									</xsd:simpleType>
								</xsd:element>
								<xsd:element name="ProdCd" minOccurs="0" type="str:TypeProdCd">
									<xsd:annotation>
										<xsd:documentation>Product Code</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
								<xsd:element name="ProdInstId" type="str:TypeProdInstId">
									<xsd:annotation>
										<xsd:documentation>Product Instance ID</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
					<xsd:element name="Cust">
						<xsd:annotation>
							<xsd:documentation>CUSTOMER</xsd:documentation>
						</xsd:annotation>
						<xsd:complexType>
							<xsd:sequence>
								<xsd:element name="CustId" type="str:TypeCustId">
									<xsd:annotation>
										<xsd:documentation>Customer ID</xsd:documentation>
									</xsd:annotation>
								</xsd:element>
							</xsd:sequence>
						</xsd:complexType>
					</xsd:element>
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- REQUESTED CUSTOMER FACING SERVICE INSTANCE STATUS: FORMAT: AN..10 -->
	<xsd:simpleType name="ReqCfsInstStat">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
			<xsd:enumeration value="ACTIVE">
				<xsd:annotation>
					<xsd:documentation>Product or service is active</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="ALL">
				<xsd:annotation>
					<xsd:documentation>Return all statuses</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="INACTIVE">
				<xsd:annotation>
					<xsd:documentation>Porduct or service is inactive</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="SUSPEND">
				<xsd:annotation>
					<xsd:documentation>Product or service has been suspended</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- CUSTOMER ID: FORMAT: AN..100 -->
	<xsd:simpleType name="TypeCustId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- DATE 10: FORMAT: AN10 -->
	<xsd:simpleType name="TypeDate10">
		<xsd:restriction base="xsd:date"/>
	</xsd:simpleType>
	<!-- PRODUCT CODE: FORMAT: AN..50 -->
	<xsd:simpleType name="TypeProdCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="50"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PRODUCT INSTANCE ID: FORMAT: AN..100 -->
	<xsd:simpleType name="TypeProdInstId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- WSO IDENTIFIER: FORMAT: AN..100 -->
	<xsd:simpleType name="TypeWsoId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== dhananjay4985/wsclient/WSClientExample/src/main/resources/wsdl/GetInstalledBaseRequest-v1.1-Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Sample Message of message hierarchy                                          -->
<!-- Message:             Get Installed Base Request v1.1                             -->
<!-- Transaction:         IB - Installed Base                                         -->
<!-- Datamodel:           ZSmart Communication Datamodel, version 1.0                 -->
<!-- XML tagset used:     KpnML                                                       -->
<!-- Generated at:        08-12-2016 17:14:15                                         -->
<!-- Generated using:     EC-Design 1.6.1* (http://www.ec-design.nl)                  -->
<!-- Generated by:        Frans van Basten                                            -->
<!-- Organisation:        KPN (KPN)                                                   -->
<!-- NOTE:    This sample message was generated automatically: manual modifications will be lost -->
<GetInstalledBaseRequest-v1 xsi:schemaLocation="http://services.kpn.com/Messages/GetInstalledBaseRequest-v1 GetInstalledBaseRequest-v1.1.xsd"
		xmlns="http://services.kpn.com/Messages/GetInstalledBaseRequest-v1"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<OrigReqerId>ORIGREQID0H7G6F7B234C8A</OrigReqerId>
	<ReqParams>
		<ReqProdInstStat>ACTIVE</ReqProdInstStat>
	</ReqParams>
	<Prod>
		<ProdType/>
		<ProdCd>PROD007</ProdCd>
		<ProdInstId>PRODUCTINST123321</ProdInstId>
	</Prod>
</GetInstalledBaseRequest-v1>
